version: '3.8'

services:
  configuration-master:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.master
    hostname: configuration-master
    container_name: cloudian-master
    platform: linux/amd64
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    volumes:
      - lvvl_my_files:/myfiles
    networks:
      - cluster-network2
    stdin_open: true
    tty: true
    command: |
      bash -c "
        /usr/sbin/sshd -D &
        tail -f /dev/null
      "

  worker:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.node
    hostname: node
    platform: linux/amd64
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    networks:
      - cluster-network2
    stdin_open: true
    tty: true
    deploy:
      replicas: 3
    command: |
      bash -c "
        /usr/sbin/sshd -D &
        tail -f /dev/null
      "
networks:
  cluster-network2:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16

volumes:
  lvvl_my_files:
    external: true
