version: '3.8'

services:
  configuration-master:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.master
    hostname: configuration-master
    container_name: configuration-master
    platform: linux/amd64
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    volumes:
      - lvvl_my_files:/myfiles
    networks:
      - cluster-network
    stdin_open: true
    tty: true
    command: |
      bash -c "
        /usr/sbin/sshd -D &
        tail -f /dev/null
      "

  node1:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.node
    hostname: node1
    container_name: node1
    platform: linux/amd64
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    networks:
      - cluster-network
    stdin_open: true
    tty: true
    command: |
      bash -c "
        /usr/sbin/sshd -D &
        tail -f /dev/null
      "

  node2:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.node
    hostname: node2
    container_name: node2
    platform: linux/amd64
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    networks:
      - cluster-network
    stdin_open: true
    tty: true
    command: |
      bash -c "
        /usr/sbin/sshd -D &
        tail -f /dev/null
      "

  node3:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.node
    hostname: node3
    container_name: node3
    platform: linux/amd64
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    networks:
      - cluster-network
    stdin_open: true
    tty: true
    command: |
      bash -c "
        /usr/sbin/sshd -D &
        tail -f /dev/null
      "

networks:
  cluster-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  lvvl_my_files:
    external: true
